// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mucfueexayxqogwgtmvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11Y2Z1ZWV4YXl4cW9nd2d0bXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTY5ODAsImV4cCI6MjA2MzkzMjk4MH0.Pnv470bTkipaosVRJ7btcblqCBT0chhSaN8D40E42Jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);